services:
  - type: web
    name: searxng-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: SEARXNG_DEBUG
        value: 0
      - key: SEARXNG_BIND_ADDRESS
        value: 127.0.0.1
      - key: SEARXNG_PORT
        value: 8888
      - key: PORT
        value: 10000
      - key: SEARXNG_SECRET
        generateValue: true
